# Generated by Django 6.0.6 on 2026-07-14 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adminname', models.CharField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('ShortName', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=100)),
                ('MoNumber', models.CharField(max_length=15)),
                ('Pass', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Solve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyName', models.CharField(max_length=100)),
                ('ShortName', models.CharField(max_length=20)),
                ('Subject', models.CharField(max_length=100)),
                ('Answer', models.TextField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='solve/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RollNo', models.CharField(max_length=20, unique=True)),
                ('Enroll', models.CharField(max_length=50, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Div', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=100)),
                ('Pass', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enroll', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=20)),
                ('Sub', models.CharField(max_length=100)),
                ('Doubt', models.TextField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='doubts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Solved')], default='pending', max_length=10)),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='Doubt.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sem', models.IntegerField()),
                ('Faze', models.IntegerField()),
                ('Note', models.FileField(upload_to='notes/%Y/%m/')),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Doubt.faculty')),
            ],
            options={
                'verbose_name_plural': 'Notes',
                'ordering': ['-id'],
            },
        ),
    ]
