# Generated by Django 6.0.5 on 2026-07-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='Solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='SolutionPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='solutions/'),
        ),
    ]
