# Generated by Django 6.0.5 on 2026-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubt', '0002_doubt_solution_doubt_solutionphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='RollNo',
            field=models.CharField(max_length=20),
        ),
    ]
