# Generated by Django 6.0.5 on 2026-08-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doubt', '0005_doubtcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
